export interface Commitments {
   Id:number;
   placeid:number;
   PlaceName:string;
  SUBID:number;
   SubName:string;

  EGross:any;
  EPF:any;
          EESI:any;
          EEPF:any;
          EEESI:any;
          ENet:any;
          LGross:any
          ;
          LPF:any;
          LESI:any;
          LEPF:any;
          LEESI:any;
          LNET:any;
          LLIC:any;
          PELIC:any;
          PEGross:any;
          PEPF:any;
          PEESI:any;
          PEEPF:any;
          PEEESI:any;
          PENet:any;
          PLGross:any;
          PLPF:any;
          PLESI:any;
          PLEPF:any;
          PLEESI:any;
          PLNET:any;
          PLLIC:any;
          ELIC:any;
}
